In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.datasets import make_regression

In [4]:
X1,y1=make_regression(n_samples=1000,n_features=5,noise=0.3)

In [5]:
X1

array([[-0.61682628, -0.78331341, -0.08147558, -0.65336015,  0.10415078],
       [-1.07196614,  0.07647736,  0.53446502, -0.22347006, -0.09299939],
       [-0.95908146, -0.78602902, -0.08406325,  0.30125208, -1.30226105],
       ...,
       [ 0.78138913,  0.66458813,  0.9515835 ,  2.05639553, -0.5281496 ],
       [ 0.18405567, -0.8323891 ,  0.50500621, -1.86206408, -0.03129578],
       [ 0.66745201,  2.03921226,  2.01129178,  0.94982361,  0.18808305]])

In [7]:
y1

array([-1.40946328e+02, -8.18867978e+01, -1.69110257e+02,  6.69134994e+01,
       -1.32862360e+01, -2.23531275e+02,  1.24567309e+02, -3.78295467e+01,
        1.21979989e+02,  8.63457307e+01,  1.17343152e+02, -1.80008432e+01,
        3.87579983e+01,  6.88783211e+01, -1.69377688e+02,  7.35870160e+01,
       -1.12188572e+02, -1.90440645e+02, -7.24420720e+01, -1.95638692e+02,
       -2.08653185e+01,  2.06981509e+02,  3.18160691e+01,  8.32132044e+01,
       -3.53706758e+01,  3.46473479e+01,  5.65091246e+01,  2.58472080e+02,
        3.91690001e+01,  4.74412271e+01,  3.32771256e+01,  8.14475787e+01,
       -9.70383445e+01, -2.28771964e+02, -4.34089299e+00, -8.11660723e+00,
       -1.41609627e+01, -1.90631971e+02, -8.14926340e+01, -1.54765048e+02,
       -2.81876024e+01,  1.12245612e+02,  8.38970254e+00,  3.10990026e+01,
       -1.35265081e+01,  4.14568163e+00,  1.90490021e+02,  6.92259778e+01,
       -3.63969333e+01, -1.05692877e+02, -2.05265240e+01, -1.20643533e+02,
       -5.99995175e+01, -

In [8]:
X_train1,X_test1,y_train1,y_test1=train_test_split(X1,y1,test_size=0.25,random_state=43)

In [12]:
model=DecisionTreeRegressor()

In [13]:
model.fit(X_train1,y_train1)

DecisionTreeRegressor()

In [15]:
y_pred1=model.predict(X_test1)

In [16]:
mse=mean_squared_error(y_test1,y_pred1)

In [17]:
mse

2420.178005541605

In [18]:
r2_score(y_test1,y_pred1)

0.8255381962204111

In [ ]:
mse

In [31]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score,mean_squared_error
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split

In [22]:
(X,y)=make_regression(n_samples=1000,n_features=5,noise=0.3)

In [23]:
X

array([[ 1.87079503,  1.39966575, -0.15513657,  1.16103243, -0.38733542],
       [-0.12867136, -1.58981149,  0.20916401,  0.67717328,  0.635987  ],
       [-0.84369049, -2.11289946, -0.45149262,  0.47911303,  1.41979136],
       ...,
       [ 0.71156783, -0.08392603, -0.06609234, -0.01262453,  0.37604555],
       [ 1.64508243,  0.92582217,  0.49863921,  0.30821599,  1.78263537],
       [-0.3156595 ,  0.36802698, -0.14437066, -0.81340537, -0.96262083]])

In [24]:
y

array([ 1.11544408e+02,  3.57106799e+01, -3.97446470e+00,  3.10206340e+01,
       -2.52418469e+01, -5.24983794e+01, -3.95465047e+01,  5.99364453e+01,
        5.12961490e+01, -1.69753073e+02, -5.16954127e+01,  2.73199704e+00,
        9.88995677e+00,  3.27752367e+01, -4.12364416e+01, -4.88570824e+01,
        5.92396168e+01, -1.26837930e+02,  6.73388462e+01, -1.08307119e+02,
        7.17239512e+01,  1.72321858e+01, -1.00447209e+01,  7.35003161e+01,
        1.23487172e+02, -5.49487102e+01, -4.05130366e+01, -8.49746499e+01,
        1.16527964e+02,  5.72783881e+00,  5.36138574e+01,  1.10570312e+02,
        8.88145818e+01,  5.80830463e+01, -5.20688687e+00,  1.10256105e+01,
        6.42431852e+01,  3.11731168e+01,  2.19922142e+01,  5.58973201e+01,
        8.67905225e+00, -7.24327129e+01, -2.32648890e+02, -1.52884074e+02,
        7.50139734e+01, -1.37674487e+02, -5.34215140e+01,  7.10404157e+01,
        1.34167135e+02, -9.65374811e+01,  3.30753709e+01,  8.63840895e+01,
       -5.73029859e+01, -

In [35]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=43)

In [36]:
model=DecisionTreeRegressor()

In [37]:
model.fit(X_train,y_train)

DecisionTreeRegressor()

In [38]:
y_pred=model.predict(X_test)

In [39]:
mse=mean_squared_error(y_test,y_pred)

In [40]:
mse

1838.4261292353451

In [41]:
r2_score(y_test,y_pred)

0.7788646438967073