In [36]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.model_selection import train_test_split,GridSearchCV

In [37]:
df=pd.read_csv(r"F:\Datasets\iris_prac.csv")

In [38]:
df.head()

Col1  Col2  Col3  Col4       Target
0   5.1   3.5   1.4   0.2  Iris-setosa
1   4.9   3.0   1.4   0.2  Iris-setosa
2   4.7   3.2   1.3   0.2  Iris-setosa
3   4.6   3.1   1.5   0.2  Iris-setosa
4   5.0   3.6   1.4   0.2  Iris-setosa

In [39]:
X=df.drop("Target",axis=1)

In [40]:
y=df["Target"]

In [41]:
X

Col1  Col2  Col3  Col4
0     5.1   3.5   1.4   0.2
1     4.9   3.0   1.4   0.2
2     4.7   3.2   1.3   0.2
3     4.6   3.1   1.5   0.2
4     5.0   3.6   1.4   0.2
..    ...   ...   ...   ...
145   6.7   3.0   5.2   2.3
146   6.3   2.5   5.0   1.9
147   6.5   3.0   5.2   2.0
148   6.2   3.4   5.4   2.3
149   5.9   3.0   5.1   1.8

[150 rows x 4 columns]

In [42]:
y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Target, Length: 150, dtype: object

In [43]:
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.8,random_state=23)

In [44]:
model=DecisionTreeClassifier(criterion="gini", max_depth=2, max_features=2)

In [45]:
model.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=2, max_features=2)

In [28]:
model.score(X_train,y_train)

0.9583333333333334

In [29]:
y_pred=model.predict(X_test)

In [30]:
accuracy_score(y_test,y_pred)

0.9666666666666667

In [31]:
confusion_matrix(y_test,y_pred)

array([[12,  0,  0],
       [ 0,  8,  0],
       [ 0,  1,  9]], dtype=int64)

In [32]:
print(classification_report(y_test,y_pred))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        12
Iris-versicolor       0.89      1.00      0.94         8
 Iris-virginica       1.00      0.90      0.95        10

       accuracy                           0.97        30
      macro avg       0.96      0.97      0.96        30
   weighted avg       0.97      0.97      0.97        30



In [74]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.model_selection import train_test_split

In [37]:
df=pd.read_csv(r"F:\Datasets\iris_prac.csv")

In [38]:
df.head()

Col1  Col2  Col3  Col4       Target
0   5.1   3.5   1.4   0.2  Iris-setosa
1   4.9   3.0   1.4   0.2  Iris-setosa
2   4.7   3.2   1.3   0.2  Iris-setosa
3   4.6   3.1   1.5   0.2  Iris-setosa
4   5.0   3.6   1.4   0.2  Iris-setosa

In [39]:
X=df.drop("Target",axis=1)

In [40]:
y=df["Target"]

In [41]:
X

Col1  Col2  Col3  Col4
0     5.1   3.5   1.4   0.2
1     4.9   3.0   1.4   0.2
2     4.7   3.2   1.3   0.2
3     4.6   3.1   1.5   0.2
4     5.0   3.6   1.4   0.2
..    ...   ...   ...   ...
145   6.7   3.0   5.2   2.3
146   6.3   2.5   5.0   1.9
147   6.5   3.0   5.2   2.0
148   6.2   3.4   5.4   2.3
149   5.9   3.0   5.1   1.8

[150 rows x 4 columns]

In [42]:
y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Target, Length: 150, dtype: object

In [32]:
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.8,random_state=100)

In [33]:
model=DecisionTreeClassifier(criterion="gini", max_depth=2, max_features=2)

In [46]:
model.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=2, max_features=2)

In [84]:
y_pred=model.predict(X_test)

In [85]:
model.score(X_train,y_train)

0.95

In [86]:
accuracy_score(y_test,y_pred)

0.9666666666666667

In [87]:
confusion_matrix(y_test,y_pred)

array([[11,  0,  0],
       [ 0,  5,  1],
       [ 0,  0, 13]], dtype=int64)

In [73]:
print(classification_report(y_test,y_pred))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      0.80      0.89        10
Iris-versicolor       0.82      1.00      0.90         9
 Iris-virginica       1.00      1.00      1.00        11

       accuracy                           0.93        30
      macro avg       0.94      0.93      0.93        30
   weighted avg       0.95      0.93      0.93        30



In [7]:
df=pd.read_excel(r"F:\Datasets\Play Tennis.xlsx")

In [8]:
df.head()

outlook  temp humidity    wind play
0     sunny   hot     high    weak   no
1     sunny   hot     high  strong   no
2  overcast   hot     high    weak  yes
3     rainy  mild     high    weak  yes
4     rainy  cool   normal    weak  yes

In [9]:
X=df.drop("play",axis=1)

In [10]:
y=df["play"]

In [11]:
X

outlook  temp humidity    wind
0      sunny   hot     high    weak
1      sunny   hot     high  strong
2   overcast   hot     high    weak
3      rainy  mild     high    weak
4      rainy  cool   normal    weak
5      rainy  cool   normal  strong
6   overcast  cool   normal  strong
7      sunny  mild     high    weak
8      sunny  cool   normal    weak
9      rainy  mild   normal    weak
10     sunny  mild   normal  strong
11  overcast  mild     high  strong
12  overcast   hot   normal    weak
13     rainy  mild     high  strong

In [12]:
y

0      no
1      no
2     yes
3     yes
4     yes
5      no
6     yes
7      no
8     yes
9     yes
10    yes
11    yes
12    yes
13     no
Name: play, dtype: object

In [29]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=42)

In [48]:
model=DecisionTreeClassifier(criterion="gini", max_depth=2, max_features=2)

In [49]:
model.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=2, max_features=2)

In [50]:
y_pred=model.predict(X_test)

In [53]:
model.score(X_train,y_train)

0.9583333333333334

In [59]:
accuracy_score(y_test,y_pred)

0.9333333333333333

In [55]:
confusion_matrix(y_test,y_pred)

array([[12,  0,  0],
       [ 0,  7,  1],
       [ 0,  1,  9]], dtype=int64)

In [58]:
print(classification_report(y_test,y_pred))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        12
Iris-versicolor       0.88      0.88      0.88         8
 Iris-virginica       0.90      0.90      0.90        10

       accuracy                           0.93        30
      macro avg       0.92      0.92      0.92        30
   weighted avg       0.93      0.93      0.93        30

