In [25]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_regression

In [3]:
(X,y)=make_regression (n_samples=30,n_features=1,noise=15)

In [7]:
lr=0.01
m=0
b=0
for i in range(40):
    m_slope=-2*np.sum(X.ravel()*(y-m*X.ravel()-b))
    b_slope=-2*np.sum(y-m*X.ravel()-b)
    m=m-(lr*m_slope)
    b=b-(lr*b_slope)

In [8]:
m

71.1414783399778

In [9]:
b

-0.5860577402909269

In [10]:
model=LinearRegression()

In [11]:
model.fit(X,y)

LinearRegression()

In [12]:
model.coef_

array([71.14147834])

In [13]:
model.intercept_

-0.586057740290916

In [24]:
(X,y)=make_regression (n_samples=20,n_features=2,noise=10)

In [26]:
lr=0.05
m=np.array([0,0])
b=0
for i in range(200):
    m_slope=-2*np.mean(X.T*(y-np.dot(m,X.T)-b),axis=1)
    b_slope=-2*np.mean(y-np.dot(m,X.T)-b)
    m=m-(lr*m_slope)
    b=b-(lr*b_slope)

In [28]:
b


-2.472391736614269

In [29]:
m

array([90.68587924, 38.34395076])

In [30]:
model=LinearRegression()
model.fit(X,y)

LinearRegression()

In [31]:
model.coef_

array([90.68588757, 38.34395444])

In [32]:
model.intercept_

-2.472386073474567