In [17]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split

In [2]:
df=pd.read_csv(r"F:\Datasets\Salary_dataset.csv")

In [3]:
df.head()

Unnamed: 0  YearsExperience   Salary
0           0              1.2  39344.0
1           1              1.4  46206.0
2           2              1.6  37732.0
3           3              2.1  43526.0
4           4              2.3  39892.0

In [4]:
df.drop("Unnamed: 0",axis=1,inplace=True)

In [5]:
df.head()

YearsExperience   Salary
0              1.2  39344.0
1              1.4  46206.0
2              1.6  37732.0
3              2.1  43526.0
4              2.3  39892.0

In [6]:
X=df.drop("Salary",axis=1)

In [7]:
y=df["Salary"]

In [8]:
X

YearsExperience
0               1.2
1               1.4
2               1.6
3               2.1
4               2.3
5               3.0
6               3.1
7               3.3
8               3.3
9               3.8
10              4.0
11              4.1
12              4.1
13              4.2
14              4.6
15              5.0
16              5.2
17              5.4
18              6.0
19              6.1
20              6.9
21              7.2
22              8.0
23              8.3
24              8.8
25              9.1
26              9.6
27              9.7
28             10.4
29             10.6

In [9]:
y

0      39344.0
1      46206.0
2      37732.0
3      43526.0
4      39892.0
5      56643.0
6      60151.0
7      54446.0
8      64446.0
9      57190.0
10     63219.0
11     55795.0
12     56958.0
13     57082.0
14     61112.0
15     67939.0
16     66030.0
17     83089.0
18     81364.0
19     93941.0
20     91739.0
21     98274.0
22    101303.0
23    113813.0
24    109432.0
25    105583.0
26    116970.0
27    112636.0
28    122392.0
29    121873.0
Name: Salary, dtype: float64

In [10]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=234)

In [11]:
model=LinearRegression()

In [12]:
model.fit(X_train,y_train)

LinearRegression()

In [13]:
y_pred=model.predict(X_test)

In [14]:
r2_score(y_test,y_pred)

0.9470549655955153

In [35]:
(X,y)= make_regression(n_samples=30,n_features=1,noise=15)

In [21]:
X

array([[ 0.81217998],
       [ 0.3614788 ],
       [ 2.11130315],
       [-0.66928292],
       [-0.48397781],
       [ 1.17467343],
       [ 0.42968759],
       [ 1.34993053],
       [ 0.08644462],
       [ 0.57416565],
       [ 0.48165663],
       [-1.05639579],
       [ 0.77578811],
       [ 0.56722755],
       [ 0.62382406],
       [-0.49663922],
       [-0.07566622],
       [-0.9152375 ],
       [-0.00367522],
       [ 0.13638027],
       [-0.59701385],
       [-1.14435601],
       [-1.12762249],
       [-0.3286453 ],
       [-0.15398015],
       [-0.10177565],
       [-0.43970188],
       [ 0.11223276],
       [-0.87917104],
       [-0.93056035]])

In [38]:
lr=0.01
m=0
b=0
for i in range(40):
    m_slope=-2*np.sum((y-m*X.ravel()-b)*X.ravel())
    b_slope=-2*np.sum(y-m*X.ravel()-b)
    m=m-(lr*m_slope)
    b=b-(lr*b_slope)
    y_pred=m*X.ravel()+b

In [39]:
m

77.65060904454332

In [40]:
b

10.61600578040455

In [44]:
model=LinearRegression()

In [45]:
model.fit(X,y)

LinearRegression()

In [46]:
model.coef_

array([77.65060905])

In [47]:
model.intercept_

10.616005781052916

In [48]:
(X,y)= make_regression(n_samples=20,n_features=2,noise=10)

In [51]:
lr=0.05
m=np.array([0,0])
b=0
for i in range(200):
    m_slope=-2*np.mean(X.T*(y-np.dot(m,X.T)-b),axis=1)
    b_slope=-2*np.mean(y-np.dot(m,X.T)-b)
    m=m-(lr*m_slope)
    b=b-(lr*b_slope)
   

In [52]:
m

array([61.66643102, 84.66683291])

In [53]:
b

-2.1280280017251645

In [54]:
model=LinearRegression()

In [55]:
model.fit(X,y)

LinearRegression()

In [56]:
model.coef_

array([61.66640594, 84.66685365])

In [58]:
model.intercept_

-2.128049058314224