In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix, classification_report
from sklearn.datasets import load_digits

In [5]:
digit=load_digits()

In [13]:
digit.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [16]:
digit.target

array([0, 1, 2, ..., 8, 9, 8])

In [19]:
X=digit.data
y=digit.target

In [21]:
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.7,random_state=23)

In [34]:
model=RandomForestClassifier(n_estimators=150)

In [35]:
model.fit(X_train,y_train)

RandomForestClassifier(n_estimators=150)

In [36]:
y_pred=model.predict(X_test)

In [37]:
accuracy_score(y_test,y_pred)

0.9777777777777777

In [38]:
confusion_matrix(y_test,y_pred)

array([[46,  0,  0,  0,  1,  0,  0,  0,  0,  0],
       [ 0, 61,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 51,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 47,  0,  1,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 54,  0,  0,  1,  0,  0],
       [ 0,  0,  0,  0,  1, 58,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 53,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 48,  0,  1],
       [ 0,  2,  0,  0,  0,  1,  0,  0, 48,  0],
       [ 0,  0,  0,  0,  0,  3,  0,  0,  1, 62]], dtype=int64)

In [39]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      0.98      0.99        47
           1       0.97      1.00      0.98        61
           2       1.00      1.00      1.00        51
           3       1.00      0.98      0.99        48
           4       0.96      0.98      0.97        55
           5       0.92      0.98      0.95        59
           6       1.00      1.00      1.00        53
           7       0.98      0.98      0.98        49
           8       0.98      0.94      0.96        51
           9       0.98      0.94      0.96        66

    accuracy                           0.98       540
   macro avg       0.98      0.98      0.98       540
weighted avg       0.98      0.98      0.98       540



In [40]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_digits
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [41]:
digit.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [42]:
digit.target

array([0, 1, 2, ..., 8, 9, 8])

In [43]:
X=digit.data

In [44]:
y=digit.target

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.7,random_state=23)

In [45]:
model=RandomForestClassifier(n_estimators=150)

In [46]:
model.fit(X_train,y_train)

RandomForestClassifier(n_estimators=150)

In [47]:
y_pred=model.predict(X_test)

In [49]:
accuracy_score(y_test,y_pred)

0.975925925925926

In [48]:
confusion_matrix(y_test,y_pred)

array([[46,  0,  0,  0,  1,  0,  0,  0,  0,  0],
       [ 0, 61,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1, 50,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 47,  0,  1,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 54,  0,  0,  1,  0,  0],
       [ 0,  0,  0,  0,  1, 58,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 53,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 48,  0,  1],
       [ 0,  1,  0,  0,  0,  2,  0,  0, 48,  0],
       [ 0,  0,  0,  0,  0,  3,  0,  0,  1, 62]], dtype=int64)

In [ ]:
print(classification_report(y_test,y_pred))