In [20]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_regression


In [2]:
df= pd.read_csv(r"C:\Users\Shuba\Downloads\Salary_dataset.csv")

In [4]:
df.head()

Unnamed: 0  YearsExperience   Salary
0           0              1.2  39344.0
1           1              1.4  46206.0
2           2              1.6  37732.0
3           3              2.1  43526.0
4           4              2.3  39892.0

In [5]:
df.drop("Unnamed: 0",axis=1,inplace=True)

In [6]:
df.head()

YearsExperience   Salary
0              1.2  39344.0
1              1.4  46206.0
2              1.6  37732.0
3              2.1  43526.0
4              2.3  39892.0

In [11]:
X=df.drop("Salary",axis=1)

In [8]:
y=df["Salary"]

In [9]:
y

0      39344.0
1      46206.0
2      37732.0
3      43526.0
4      39892.0
5      56643.0
6      60151.0
7      54446.0
8      64446.0
9      57190.0
10     63219.0
11     55795.0
12     56958.0
13     57082.0
14     61112.0
15     67939.0
16     66030.0
17     83089.0
18     81364.0
19     93941.0
20     91739.0
21     98274.0
22    101303.0
23    113813.0
24    109432.0
25    105583.0
26    116970.0
27    112636.0
28    122392.0
29    121873.0
Name: Salary, dtype: float64

In [12]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=234)

In [13]:
model=LinearRegression()

In [14]:
model.fit(X_train,y_train)

LinearRegression()

In [15]:
y_pred=model.predict(X_test)

In [18]:
r2_score(y_test,y_pred)

0.9470549655955153

In [19]:
model.predict([[4.5]])

C:\Users\Shuba\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([67152.9034412])

In [22]:
(X,y)=make_regression(n_samples=30,n_features=1,noise=15)

In [23]:
X

array([[-1.25033926],
       [ 0.38957665],
       [ 2.25836484],
       [-1.69412375],
       [ 1.74740521],
       [-0.19418174],
       [-0.54712112],
       [-0.56609547],
       [-0.70509836],
       [-0.5808747 ],
       [ 1.18073147],
       [-1.26353675],
       [-0.76972772],
       [-0.56173613],
       [ 0.20380236],
       [-0.58298265],
       [-0.54698959],
       [-0.02576919],
       [-0.6948757 ],
       [-0.34416865],
       [-0.55748572],
       [-0.29442009],
       [ 0.3366726 ],
       [-1.21069602],
       [-1.38841013],
       [ 0.68898173],
       [ 0.60355917],
       [ 1.20117633],
       [ 0.7756938 ],
       [-0.93163668]])

In [24]:
y

array([ -91.30350345,   41.43069781,  155.32005477, -118.54905097,
         99.5282958 ,    2.63935404,  -22.65504086,  -39.621215  ,
        -73.0675408 ,  -42.59604205,   88.24620078,  -52.7255167 ,
        -51.73828697,  -26.96967732,   14.76354522,  -38.32915905,
        -33.1360485 ,  -21.57392034,  -49.52120007,  -17.98583088,
        -54.92189066,  -16.20114286,   11.85667851,  -50.73248624,
       -104.91987582,    9.72509684,    2.95913389,   94.69388226,
         38.79779152,  -75.58359723])

In [96]:
lr=0.01
m=0
b=0
for i in range(40):
    m_slope=-2*np.sum((y-m*X.ravel()-b)*X.ravel())
    b_slope=-2*np.sum(y-m*X.ravel()-b)
    m=m-(lr*m_slope)
    b=b-(lr*b_slope)
    y_pred=m*X.ravel()+b
    

In [97]:
m

63.97110690525785

In [98]:
b

-2.7189531483230325

In [26]:
model=LinearRegression()

In [99]:
model.fit(X,y)

LinearRegression()

In [100]:
model.coef_

array([63.97110691])

In [101]:
model.intercept_

-2.7189531477434077

In [108]:
(X,y)=make_regression(n_samples=20,n_features=2,noise=15)

In [110]:
lr=0.05
m=np.array([0,0])
b=0

for i in range(2000):
    m_slope=-2*np.mean(X.T*(y-np.dot(m,X.T)-b),axis=1)
    b_slope=-2*np.mean(y-np.dot(m,X.T)-b)
    m=m-(lr*m_slope)
    b=b-(lr*b_slope)
   

In [116]:
m

array([ 3.8256946, 97.0391045])

In [117]:
b

1.1058157585371045

In [111]:
model=LinearRegression()

In [112]:
model.fit(X,y)

LinearRegression()

In [114]:
model.coef_

array([ 3.8256946, 97.0391045])

In [115]:
model.intercept_

1.1058157585371262