In [1]:
import numpy as np

In [2]:
arr1=np.arange(1,37).reshape(6,6)

In [3]:
arr1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [13]:
arr1[0:5:2,0:3:1]

array([[ 1,  2,  3],
       [13, 14, 15],
       [25, 26, 27]])

In [21]:
arr1[[1,2,5],1:4:1]

array([[ 8,  9, 10],
       [14, 15, 16],
       [32, 33, 34]])

In [37]:
arr1[[1,3,5],1::2]

array([[ 8, 10, 12],
       [20, 22, 24],
       [32, 34, 36]])

In [38]:
arr1=np.

In [39]:
arr1

array([0, 1, 2])

In [45]:
arr1=np.random.choice(range(10),4).reshape(2,2)

In [46]:
arr2=np.random.choice(range(10),4).reshape(2,2)

In [48]:
arr1,arr2

(array([[8, 9],
        [5, 1]]),
 array([[0, 5],
        [0, 0]]))

In [49]:
arr1+arr2

array([[ 8, 14],
       [ 5,  1]])

In [50]:
arr1-arr2

array([[8, 4],
       [5, 1]])

In [51]:
arr1+2

array([[10, 11],
       [ 7,  3]])

In [55]:
arr1-3
arr1
arr2

array([[0, 5],
       [0, 0]])

In [56]:
arr1

array([[8, 9],
       [5, 1]])

In [59]:
arr2=np.random.choice(range(10),4).reshape(2,2)

In [61]:
arr2

array([[2, 3],
       [9, 2]])

In [62]:
arr1

array([[8, 9],
       [5, 1]])

In [63]:
arr2

array([[2, 3],
       [9, 2]])

In [64]:
arr1*arr2

array([[16, 27],
       [45,  2]])

In [65]:
arr3=np.dot(arr1,arr2)

In [66]:
arr3

array([[97, 42],
       [19, 17]])

In [67]:
arr1/arr2

array([[4.        , 3.        ],
       [0.55555556, 0.5       ]])

In [71]:
arr4=np.arange(10).reshape(2,5)
arr4

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [72]:
arr5=np.linspace(4,10,11)

In [73]:
arr5

array([ 4. ,  4.6,  5.2,  5.8,  6.4,  7. ,  7.6,  8.2,  8.8,  9.4, 10. ])

In [74]:
arr6=np.linspace(1,10,5)

In [75]:
arr6

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [85]:
arr1=np.random.randint(1,9,6).reshape(3,2)

In [86]:
arr1

array([[8, 8],
       [6, 7],
       [8, 4]])

In [88]:
arr2=np.array([[6,8]])

In [89]:
arr2

array([[6, 8]])

In [110]:
arr4=np.concatenate((arr1,arr2),axis=0)

In [111]:
arr3

array([[8, 8],
       [6, 7],
       [8, 4],
       [6, 8]])

In [117]:
arr1=np.random.randint(1,9,6).reshape(3,2)
arr1

array([[4, 8],
       [5, 4],
       [6, 8]])

In [118]:
arr2=np.random.randint(1,9,6).reshape(3,2)
arr2

array([[2, 8],
       [4, 5],
       [2, 4]])

In [123]:
arr3=np.concatenate((arr1,arr2),axis=1)

In [124]:
arr3

array([[4, 8, 2, 8],
       [5, 4, 4, 5],
       [6, 8, 2, 4]])

In [127]:
arr1=np.random.choice(range(10),6).reshape(3,2)

In [128]:
arr1

array([[4, 3],
       [6, 1],
       [1, 0]])

In [134]:
arr1=np.random.randint(34)

In [135]:
arr1

33

In [138]:
arr2=np.random.randint(1,3,3)

In [139]:
arr2

array([2, 1, 1])

In [142]:
arr3=np.random.choice(range(10),6).reshape(3,2)

In [143]:
arr3

array([[9, 1],
       [7, 0],
       [9, 1]])

In [144]:
arr4=np.linspace(1,10,3)

In [145]:
arr4

array([ 1. ,  5.5, 10. ])

In [163]:
arr1=np.array([[8,0],[4,6]])
arr1

array([[8, 0],
       [4, 6]])

In [164]:
arr2=np.array([[4,7],[8,5]])
arr2

array([[4, 7],
       [8, 5]])

In [165]:
arr3=np.stack((arr1, arr2),axis=1)

In [166]:
arr3

array([[[8, 0],
        [4, 7]],

       [[4, 6],
        [8, 5]]])

In [174]:
arr4=np.hstack((arr1, arr2))

In [175]:
arr4

array([[8, 0, 4, 7],
       [4, 6, 8, 5]])

In [176]:
arr1=np.random.randint(34)

In [177]:
arr1

1

In [179]:
arr2=np.random.randint(100,500,10)

In [180]:
arr2

array([491, 489, 408, 484, 466, 283, 344, 299, 160, 275])

In [181]:
arr1=np.random.rand(10)

In [182]:
arr1

array([0.15590888, 0.6116194 , 0.13195017, 0.2008047 , 0.90496832,
       0.09386907, 0.13533434, 0.02521378, 0.00336821, 0.92038862])

In [183]:
arr=np.split(arr1,(1,2))

In [184]:
arr

[array([0.15590888]),
 array([0.6116194]),
 array([0.13195017, 0.2008047 , 0.90496832, 0.09386907, 0.13533434,
        0.02521378, 0.00336821, 0.92038862])]

In [185]:
arr1=np.arange(1,25).reshape(6,4)

In [186]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [187]:
arr1[1,2]

7

In [188]:
arr1[1][2]

7

In [189]:
arr1[1:4,1:3]

array([[ 6,  7],
       [10, 11],
       [14, 15]])

In [190]:
arr6=np.arange(1,37).reshape(6,6)

In [191]:
arr6

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [193]:
arr6[2:5,2:5]

array([[15, 16, 17],
       [21, 22, 23],
       [27, 28, 29]])

In [201]:
arr6[::2, :3:1]

array([[ 1,  2,  3],
       [13, 14, 15],
       [25, 26, 27]])

In [220]:
arr6[[1,2,5],1:4]

array([[ 8,  9, 10],
       [14, 15, 16],
       [32, 33, 34]])

In [234]:
arr6[2:5:,2:5:1]

array([[15, 16, 17],
       [21, 22, 23],
       [27, 28, 29]])

In [2]:
import numpy as np
arr1=np.random.randint(34)
arr1

20

In [4]:
arr2=np.random.randint(100,500,7)
arr2

array([350, 115, 205, 163, 388, 129, 343])

In [7]:
arr3=np.linspace(0,10,5)
arr3

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [17]:
ls=[1,2,3,4,5,6,7,8,9]
arr4=np.random.choice(ls)
arr4

8

In [13]:
arr4=np.random.choice(ls,5)

In [14]:
arr4

array([3, 5, 1, 2, 2])

In [18]:
arr5=np.random.choice(ls).reshape(3,2)

ValueError: cannot reshape array of size 1 into shape (3,2)

In [19]:
arr6=np.random.choice(range(10),6).reshape(3,2)

In [20]:
arr6

array([[1, 5],
       [3, 2],
       [8, 6]])

In [21]:
arr7=np.zeros((3,2))

In [22]:
arr7

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [23]:
arr7=np.ones((3,2))

In [24]:
arr7

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [25]:
arr8=np.random.choice(range(10),6).reshape(3,2)
arr9=np.random.choice(range(10),6).reshape(3,2)

In [26]:
arr8
arr9

array([[2, 1],
       [4, 4],
       [6, 0]])

In [27]:
arr8

array([[9, 3],
       [1, 0],
       [1, 4]])

In [31]:
arr10=np.concatenate((arr8,arr9),axis=1)

In [32]:
arr10

array([[9, 3, 2, 1],
       [1, 0, 4, 4],
       [1, 4, 6, 0]])

In [36]:
arr11=np.stack((arr8,arr9),axis=1)
arr11

array([[[9, 3],
        [2, 1]],

       [[1, 0],
        [4, 4]],

       [[1, 4],
        [6, 0]]])

In [38]:
arr12=np.vstack((arr8,arr9))
arr12

array([[9, 3],
       [1, 0],
       [1, 4],
       [2, 1],
       [4, 4],
       [6, 0]])

In [39]:
arr13=np.hstack((arr8,arr9))

In [40]:
arr13

array([[9, 3, 2, 1],
       [1, 0, 4, 4],
       [1, 4, 6, 0]])

In [41]:
arr14=np.arange(1,24)

In [42]:
arr14

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23])

In [43]:
arr15=np.arange(1,37).reshape(6,6)
arr15

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [45]:
arr15[2:5,2:5]

array([[15, 16, 17],
       [21, 22, 23],
       [27, 28, 29]])

In [63]:
arr15[0::2,0:3]

array([[ 1,  2,  3],
       [13, 14, 15],
       [25, 26, 27]])

In [70]:
arr15[[1,2,5],1:4]

array([[ 8,  9, 10],
       [14, 15, 16],
       [32, 33, 34]])

In [71]:
arr16=np.arange(1,25).reshape(6,4)

In [72]:
arr16

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [74]:
np.split(arr16,(1,4))

[array([[1, 2, 3, 4]]),
 array([[ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[17, 18, 19, 20],
        [21, 22, 23, 24]])]

In [77]:
arr16[1,2]

7

In [84]:
arr16[[0,2,3]]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [90]:
arr16[:,[0,1,3]]

array([[ 1,  2,  4],
       [ 5,  6,  8],
       [ 9, 10, 12],
       [13, 14, 16],
       [17, 18, 20],
       [21, 22, 24]])

In [3]:
import numpy as np
arr1=np.random.randint(34)
arr1


0

In [4]:
arr2=np.random.randint(100,500,6)
arr2

array([307, 380, 364, 346, 351, 487])

In [6]:
ls=[1,2,3,4,5,6]
arr3=np.random.choice(ls,4)
arr3

array([6, 2, 4, 1])

In [11]:
arr4=np.random.choice(range(10),6).reshape(3,2)
arr4

array([[0, 7],
       [5, 8],
       [8, 6]])

In [13]:
arr4.max()

8

In [16]:
arr5=np.linspace(1,15,3)
arr5

array([ 1.,  8., 15.])

In [1]:
import pandas as pd

ModuleNotFoundError: No module named 'pandas'

In [2]:
import numpy as np

In [4]:
a=np.array([[2,5,7],
            [1,2,3],
            [7,8,2]])

In [5]:
b=np.linalg.eigvals(a)

In [6]:
b

array([11.72403766, -5.52328145, -0.2007562 ])

In [7]:
a=np.array([[2,5,7],
            [1,2,3],
            [7,8,2]])

In [8]:
b=np.linalg.inv(a)

In [9]:
b

array([[-1.53846154,  3.53846154,  0.07692308],
       [ 1.46153846, -3.46153846,  0.07692308],
       [-0.46153846,  1.46153846, -0.07692308]])

In [11]:
c=np.linalg.transpose(a)

AttributeError: module 'numpy.linalg' has no attribute 'transpose'

In [2]:
import numpy as np
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [3]:
arr1.ndim

1

In [4]:
arr1.shape

(5,)

In [5]:
arr1.size

5

In [6]:
arr1.dtype

dtype('int32')

In [7]:
arr1+5

array([ 6,  7,  8,  9, 10])

In [8]:
arr1*5

array([ 5, 10, 15, 20, 25])

In [10]:
arr1=[[1,2],[3,4]]
arr1

[[1, 2], [3, 4]]

In [11]:
arr2=[[5,6],[7,8]]
arr2

[[5, 6], [7, 8]]

In [14]:
np.dot(arr1,arr2)

array([[19, 22],
       [43, 50]])

In [17]:
arr1

[[1, 2], [3, 4]]

In [18]:
arr2

[[5, 6], [7, 8]]

In [22]:
arr1+arr2

[[1, 2], [3, 4], [5, 6], [7, 8]]

In [23]:
arr1=np.random.randint(1,5)

In [24]:
arr1

1

In [25]:
arr1=np.random.choice(range(10),4).reshape(2,2)

In [26]:
arr1

array([[7, 2],
       [6, 8]])

In [27]:
arr2=np.random.choice(range(10),4).reshape(2,2)

In [28]:
arr2

array([[7, 7],
       [7, 6]])

In [29]:
arr1+arr2

array([[14,  9],
       [13, 14]])

In [30]:
arr1-arr2

array([[ 0, -5],
       [-1,  2]])

In [31]:
arr1*arr2

array([[49, 14],
       [42, 48]])

In [32]:
arr1/arr2

array([[1.        , 0.28571429],
       [0.85714286, 1.33333333]])

In [34]:
arr1=np.random.choice(range(10),4).reshape(2,2)

In [35]:
arr1

array([[8, 7],
       [7, 1]])

In [36]:
arr2=np.random.choice(range(10),4).reshape(2,2)

In [37]:
arr2

array([[7, 9],
       [4, 5]])

In [40]:
arr3=np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [41]:
arr4=np.ones((2,3))

In [42]:
arr4

array([[1., 1., 1.],
       [1., 1., 1.]])

In [49]:
arr5=np.eye(3)
arr5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [50]:
arr1+arr2

array([[15, 16],
       [11,  6]])

In [51]:
arr1-arr2

array([[ 1, -2],
       [ 3, -4]])

In [52]:
arr1*arr2

array([[56, 63],
       [28,  5]])

In [53]:
np.dot(arr1,arr2)

array([[ 84, 107],
       [ 53,  68]])

In [54]:
arr1.max()

8

In [55]:
arr1.min()

1

In [56]:
arr1.mean()

5.75

In [57]:
arr1.sum()

23

In [58]:
arr1.std()

2.7726341266023544

In [60]:
arr1

array([[8, 7],
       [7, 1]])

In [61]:
arr2

array([[7, 9],
       [4, 5]])

In [62]:
np.concatenate((arr1,arr2))

array([[8, 7],
       [7, 1],
       [7, 9],
       [4, 5]])

In [63]:
np.stack((arr1,arr2))

array([[[8, 7],
        [7, 1]],

       [[7, 9],
        [4, 5]]])

In [64]:
np.hstack((arr1,arr2))

array([[8, 7, 7, 9],
       [7, 1, 4, 5]])

In [65]:
np.vstack((arr1,arr2))

array([[8, 7],
       [7, 1],
       [7, 9],
       [4, 5]])

In [69]:
np.split(arr1,(1,3))

[array([[8, 7]]), array([[7, 1]]), array([], shape=(0, 2), dtype=int32)]

In [71]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [1]:
import numpy as np

In [2]:
arr1=np.array([1,2,3,4,5,6])
arr1
arr1.ndim

1

In [3]:
arr1.shape

(6,)

In [4]:
arr1.size

6

In [5]:
arr1.dtype

dtype('int32')

In [7]:
arr2=np.zeros((2,3))
arr2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
arr3=np.ones((3,2))

In [9]:
arr3

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [10]:
arr4=np.eye(3)

In [11]:
arr4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
arr5=np.random.rand(10)
arr5

array([0.83396024, 0.68562336, 0.70544757, 0.19748916, 0.77638029,
       0.74769003, 0.77471089, 0.64104727, 0.28693494, 0.11151923])

In [17]:
arr6=np.random.randint(34)
arr6

31

In [19]:
arr7=np.random.randint(100,500,7)
arr7

array([220, 111, 344, 304, 145, 206, 265])

In [21]:
ls=[1,2,3,4,5,6]
arr8=np.random.choice(ls,4)
arr8

array([1, 1, 6, 5])

In [23]:
arr1=np.array([[1,2],[3,4]])


In [24]:
arr1

array([[1, 2],
       [3, 4]])

In [25]:
arr2=np.array([[5,6],[7,8]])
arr2

array([[5, 6],
       [7, 8]])

In [26]:
arr1+3

array([[4, 5],
       [6, 7]])

In [27]:
arr1-3

array([[-2, -1],
       [ 0,  1]])

In [28]:
arr1*5

array([[ 5, 10],
       [15, 20]])

In [30]:
arr9=np.dot(arr1,arr2)
arr9

array([[19, 22],
       [43, 50]])

In [31]:
arr1-arr2

array([[-4, -4],
       [-4, -4]])

In [32]:
arr1+arr2

array([[ 6,  8],
       [10, 12]])

In [33]:
arr1*arr2

array([[ 5, 12],
       [21, 32]])

In [34]:
arr1/arr2

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [36]:
arr10=np.arange(1,15)
arr10

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [38]:
arr11=np.linspace(1,15,3)
arr11

array([ 1.,  8., 15.])

In [41]:
arr12=np.concatenate((arr1,arr2))
arr12

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [44]:
arr13=np.stack((arr1,arr2))
arr13

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [47]:
arr14=np.vstack((arr1,arr2))
arr14

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [49]:
arr14=np.hstack((arr1,arr2))
arr14

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [51]:
arr15=np.split(arr1,(1,2))
arr15

[array([[1, 2]]), array([[3, 4]]), array([], shape=(0, 2), dtype=int32)]

In [52]:
arr1.min()

1

In [53]:
arr1.max()

4

In [54]:
arr1.sum()

10

In [55]:
arr1.mean()

2.5

In [56]:
arr1.std()

1.118033988749895

In [ ]:
l1=[1,2,3,4,5,6]
s1=

In [3]:
np.arange(1,10,3)

array([1, 4, 7])

In [3]:
arr1=np.array([1,2,3,4,5,6])

In [4]:
arr1.ndim

1

In [6]:
arr1.shape

(6,)

In [7]:
arr1.size

6

In [8]:
arr1.dtype

dtype('int32')

In [9]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.random.rand(10)

array([0.58842707, 0.95890022, 0.75717727, 0.14471075, 0.86722184,
       0.91600106, 0.86719657, 0.99981076, 0.16816424, 0.96220227])

In [13]:
np.random.randint(34)

16

In [14]:
np.random.randint(100,500,6)

array([227, 214, 471, 277, 331, 357])

In [18]:
ls=[1,2,3,4,5,6]

In [20]:
arr2=np.random.choice(ls,4)
arr2

array([6, 1, 4, 5])

In [21]:
arr1=np.array([[1,2],[3,4]])

In [22]:
arr2=np.array([[5,6],[7,8]])

In [24]:
arr1


array([[1, 2],
       [3, 4]])

In [25]:
arr2

array([[5, 6],
       [7, 8]])

In [27]:
np.concatenate((arr1,arr2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [28]:
np.stack((arr1,arr2))

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [29]:
np.vstack((arr1,arr2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [30]:
np.hstack((arr1,arr2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [32]:
np.split(arr1,(1,2))

[array([[1, 2]]), array([[3, 4]]), array([], shape=(0, 2), dtype=int32)]

In [33]:
np.dot(arr1,arr2)

array([[19, 22],
       [43, 50]])

In [34]:
arr1+3

array([[4, 5],
       [6, 7]])

In [40]:
arr1=np.arange(1,14,3)
arr1

array([ 1,  4,  7, 10, 13])

In [2]:
import numpy as np
np.linspace(1,17,40)

array([ 1.        ,  1.41025641,  1.82051282,  2.23076923,  2.64102564,
        3.05128205,  3.46153846,  3.87179487,  4.28205128,  4.69230769,
        5.1025641 ,  5.51282051,  5.92307692,  6.33333333,  6.74358974,
        7.15384615,  7.56410256,  7.97435897,  8.38461538,  8.79487179,
        9.20512821,  9.61538462, 10.02564103, 10.43589744, 10.84615385,
       11.25641026, 11.66666667, 12.07692308, 12.48717949, 12.8974359 ,
       13.30769231, 13.71794872, 14.12820513, 14.53846154, 14.94871795,
       15.35897436, 15.76923077, 16.17948718, 16.58974359, 17.        ])

In [3]:
np.random.randint(1, 10, (3, 3))

array([[1, 8, 5],
       [3, 9, 3],
       [4, 5, 2]])

In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]]) 
result = np.transpose(arr) 

In [5]:
result

array([[1, 4],
       [2, 5],
       [3, 6]])

In [11]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

In [12]:
np.dot(arr1,arr2)

32