In [1]:
import numpy as np

In [2]:
arr1=np.array([[[1,2,3],[5,6,7],[7,8,9]]])

In [3]:
arr1

array([[[1, 2, 3],
        [5, 6, 7],
        [7, 8, 9]]])

In [4]:
arr1.shape

(1, 3, 3)

In [5]:
arr1.size

9

In [6]:
arr1.dtype

dtype('int32')

In [7]:
a=np.zeros((3,2))

In [8]:
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [9]:
b=np.ones((2,2))

In [10]:
b

array([[1., 1.],
       [1., 1.]])

In [12]:
c=np.eye(2)
c

array([[1., 0.],
       [0., 1.]])

In [13]:
arr1=np.random.randint(10)
arr1

2

In [14]:
arr=np.array([1,3,5,9,7])
arr

array([1, 3, 5, 9, 7])

In [15]:
arr.ndim

1

In [19]:
arr1=np.array([[1,2,3],[4,5,6]])
arr1.ndim

2

In [17]:
arr1

2

In [20]:
arr1.ndim

2

In [21]:
arr2=np.array([[[1,2,3],[4,5,6],[7,8,9],[6,5,4]]])
arr2.ndim

3

In [22]:
arr2.shape

(1, 4, 3)

In [23]:
arr2.size

12

In [24]:
arr2.dtype

dtype('int32')

In [25]:
a=np.zeros((3,2))
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [26]:
b=np.ones((4,3))

In [27]:
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
c=np.ones((3,2),dtype='int')*3

In [29]:
c

array([[3, 3],
       [3, 3],
       [3, 3]])

In [30]:
a=[1,2,3]
b=[4,5,6]
a+b

[1, 2, 3, 4, 5, 6]

In [34]:
a=np.array([1,2,3])
b=np.array([4,5,6])
a+b

array([5, 7, 9])

In [35]:
c=[1,2,3]*3
c

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [36]:
d=np.array([1,2,3])*3
d

array([3, 6, 9])

In [38]:
e=np.eye(3,dtype='int')
e

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [39]:
arr1=np.random.randint(34)
arr1

23

In [40]:
arr2=np.random.rand(10)
arr2

array([0.04713941, 0.48689528, 0.03348825, 0.77640697, 0.19866296,
       0.39261471, 0.90531278, 0.1623956 , 0.94215861, 0.62345048])

In [41]:
arr3=np.random.randint(10)
arr3

9

In [42]:
arr4=np.random.randint(100,500,10)
arr4

array([309, 203, 360, 219, 205, 410, 245, 345, 364, 438])

In [43]:
arr5=np.random.randint(1,9,24)

In [44]:
arr5

array([8, 7, 3, 6, 4, 2, 8, 7, 7, 3, 7, 8, 1, 5, 2, 5, 2, 8, 8, 6, 2, 3,
       3, 4])

In [47]:
ls=[1,2,3,4,5,6]
arr6=np.random.choice(ls)
arr6

3

In [48]:
a=np.size

In [50]:
a.size

AttributeError: 'numpy._ArrayFunctionDispatcher' object has no attribute 'size'

In [51]:
arr5.size

24

In [52]:
nums=np.random.randint(1,9,12)
nums

array([3, 2, 2, 7, 7, 2, 6, 3, 3, 2, 2, 7])

In [53]:
nums.max()

7

In [55]:
nums.min()

2

In [56]:
nums.mean()

3.8333333333333335

In [57]:
nums.std()

2.1147629234082537

In [58]:
nums.sum()

46

In [59]:
nums.size

12

In [60]:
arr13=np.random.randint(1,9,24)
arr13

array([8, 5, 2, 1, 1, 8, 1, 6, 6, 3, 1, 7, 1, 3, 4, 8, 6, 4, 1, 7, 7, 8,
       1, 3])

In [61]:
arr13.reshape(6,4)

array([[8, 5, 2, 1],
       [1, 8, 1, 6],
       [6, 3, 1, 7],
       [1, 3, 4, 8],
       [6, 4, 1, 7],
       [7, 8, 1, 3]])

In [62]:
arr1=np.array([1,2,3,4,5,6])
arr1

array([1, 2, 3, 4, 5, 6])

In [63]:
arr1.shape

(6,)

In [64]:
arr1.size

6

In [65]:
arr1.ndim

1

In [66]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
arr2.size

6

In [68]:
arr2.shape

(2, 3)

In [69]:
arr2.ndim

2

In [70]:
arr3=np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [71]:
arr3=np.ones((3,3))
arr3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [75]:
arr3= np.eye(3)*3
arr3

array([[3., 0., 0.],
       [0., 3., 0.],
       [0., 0., 3.]])

In [77]:
arr4=np.random.randint(10)
arr4

9

In [78]:
arr5=np.random.randint(1,9,24)
arr5

array([8, 4, 5, 4, 4, 6, 7, 2, 1, 1, 2, 2, 7, 6, 3, 5, 4, 8, 2, 3, 7, 2,
       6, 6])

array([0, 1, 1, 1, 1, 3])

In [82]:
arr6=np.random.randint(ls)
arr6

array([0, 0, 1, 2, 4, 0])

In [88]:
ls=[1,2,3,4,5,6]
arr7=np.random.choice(ls,3)
arr7

array([2, 2, 1])

In [90]:
arr8=np.random.randint(1,9,24)
arr8

array([7, 4, 4, 5, 6, 2, 1, 8, 8, 8, 8, 3, 5, 8, 6, 5, 3, 3, 4, 6, 1, 7,
       5, 3])

In [91]:
arr8.min()

1

In [92]:
arr8.max()

8

In [93]:
arr8.sum()

120

In [94]:
arr8.mean()

5.0

In [95]:
arr8.std()

2.1984843263788196

In [97]:
np.square(arr8)

array([49, 16, 16, 25, 36,  4,  1, 64, 64, 64, 64,  9, 25, 64, 36, 25,  9,
        9, 16, 36,  1, 49, 25,  9])

In [98]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [99]:
arr1.ndim

1

In [100]:
arr1.shape

(5,)

In [101]:
arr1.size

5

In [102]:
arr2=np.array([[[1,2,3,],[4,5,6],[7,8,9]]])
arr2

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [103]:
arr2.shape

(1, 3, 3)

In [104]:
arr2.ndim

3

In [105]:
arr2.size

9

In [109]:
arr3=np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [110]:
arr3=np.ones((3,2))

In [111]:
arr3

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [112]:
arr4=np.eye(2)

In [113]:
arr4

array([[1., 0.],
       [0., 1.]])

In [120]:
a=[1,2,3]
b=[4,5,6]
a+b



[1, 2, 3, 4, 5, 6]

In [115]:
a=np.array([1,2,3])
b=np.array([4,5,6])
a+b

array([5, 7, 9])

In [118]:
a=np.array([1,2,3])
b=np.array([4,5,6])
a*b

array([ 4, 10, 18])

In [124]:
a=[1,2,3]
b=[4,5,6]
a*5

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [130]:
arr1=np.random.randint(10)

In [131]:
arr1

2

In [132]:
arr2=np.random.randint(100,500,5)
arr2

array([381, 163, 366, 432, 420])

In [133]:
ls=[1,2,3,4,5,6]
arr3=np.random.choice(ls)
arr3

1

In [134]:
arr3=np.random.choice(ls,4)

In [135]:
arr3

array([6, 1, 5, 2])

In [139]:
arr4=np.random.rand(10)
arr4

array([0.10965342, 0.01600319, 0.09396097, 0.29984467, 0.62658198,
       0.59549428, 0.39804765, 0.48659422, 0.84599328, 0.77949008])

In [140]:
arr1=np.array([1,2,3,4,5,6])
arr1.max()

6

In [141]:
arr1.min()

1

In [142]:
arr1.sum()

21

In [143]:
arr1.mean()

3.5

In [144]:
arr1.std()

1.707825127659933

In [145]:
arr1=np.array([1,2,34,5,6,7,8,9,9])
arr1.reshape(3,3)

array([[ 1,  2, 34],
       [ 5,  6,  7],
       [ 8,  9,  9]])

In [147]:
arr1.reshape(3,3)

array([[ 1,  2, 34],
       [ 5,  6,  7],
       [ 8,  9,  9]])

In [148]:
arr1.resize(3,3)

In [149]:
arr1

array([[ 1,  2, 34],
       [ 5,  6,  7],
       [ 8,  9,  9]])

In [152]:
arr1=np.arange(1,9,2)

In [153]:
arr1

array([1, 3, 5, 7])

In [154]:
arr=np.array([[10,20,30],[40,50,60]])
arr

array([[10, 20, 30],
       [40, 50, 60]])

In [155]:
arr.reshape(3,2)

array([[10, 20],
       [30, 40],
       [50, 60]])

In [156]:
arr.resize(3,2)

In [157]:
arr

array([[10, 20],
       [30, 40],
       [50, 60]])

In [158]:
arr=np.array([[[10,20,30],[40,50,60],[70,80,90]]])
arr

array([[[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]])

In [159]:
arr.size

9

In [160]:
arr.shape

(1, 3, 3)

In [162]:
arr.reshape(3,3)

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [163]:
arr.min()

10

In [164]:
arr.max()

90

In [166]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.concatenate((a,b))

In [167]:
c

array([1, 2, 3, 4, 5, 6])

In [175]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[1,2,3]])
c=np.concatenate((a,b),axis=1)

In [176]:
c

array([[1, 2, 3, 7, 8, 9],
       [4, 5, 6, 1, 2, 3]])

In [2]:
arr1=np.array([1,2,3,4,5,6])
arr1

array([1, 2, 3, 4, 5, 6])

In [3]:
arr1.ndim

1

In [5]:
arr1.shape

(6,)

In [6]:
arr1.size

6

In [7]:
arr1.dtype

dtype('int32')

In [8]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
np.random.rand(10)


array([0.53570071, 0.44490201, 0.30819825, 0.27480722, 0.90037205,
       0.49812786, 0.69813168, 0.10261073, 0.38334816, 0.50504182])

In [12]:
np.random.randint(34)

4

In [13]:
np.random.randint(100,500,6)

array([141, 458, 116, 322, 307, 272])

In [14]:
ls=[1,2,3,4,5,6]
np.random.choice(ls,4)

array([2, 6, 1, 2])

In [16]:
arr1=np.array([[1,2],[3,4]])
arr1

array([[1, 2],
       [3, 4]])

In [17]:
arr2=np.array([[5,6],[7,8]])
arr2

array([[5, 6],
       [7, 8]])

In [18]:
arr1+arr2

array([[ 6,  8],
       [10, 12]])

In [19]:
arr1-arr2

array([[-4, -4],
       [-4, -4]])

In [20]:
arr1*arr2

array([[ 5, 12],
       [21, 32]])

In [21]:
arr1/arr2

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [22]:
arr1.min()

1

In [23]:
arr1.max()

4

In [25]:
arr1.std()

1.118033988749895

In [26]:
arr1.mean()

2.5

In [27]:
arr1.sum()

10

In [28]:
arr1.dot(arr2)

array([[19, 22],
       [43, 50]])

In [29]:
np.concatenate((arr1,arr2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [30]:
np.stack((arr1,arr2))

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [31]:
np.vstack((arr1,arr2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [32]:
np.hstack((arr1,arr2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [33]:
np.split(arr1,(1,2))

[array([[1, 2]]), array([[3, 4]]), array([], shape=(0, 2), dtype=int32)]

In [34]:
np.arange(1,20,3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [35]:
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])